Refactor exaslct start script for better readability and fix stage order in .travis.yml

diff --git a/exaslct b/exaslct
--- a/exaslct
+++ b/exaslct
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+# This script acts as the start of exaslct the script language container build tool
+# It tries to discover if pipenv is already installed or tries to install it if it not exists.
+# After that it creates the virtual environment and install all necessary dependencies for exaslct.
+# In the end it runs exaslct_src/exaslct.py in the virtual environment.
+
 COMMAND_LINE_ARGS=$*
 SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 
@@ -23,16 +28,57 @@ run () {
     $PIPENV_BIN run python3 exaslct_src/exaslct.py $COMMAND_LINE_ARGS
 }
 
-find_via_pip () {
+find_and_run_via_pip () {
     local PIPENV_LOCATION=$(pip show pipenv | grep 'Location:'  | cut -f 2 -d " ")
     local PIPENV_BIN_IN_LOCATION=$(pip show -f pipenv | grep 'bin/pipenv$' | awk '{$1=$1};1')
     PIPENV_BIN=$(command -v "$PIPENV_LOCATION/$PIPENV_BIN_IN_LOCATION")
+    if [ -n "$PIPENV_BIN" ];
+    then
+        run "$PIPENV_BIN"
+    else
+        echo "ERROR: pipenv seems to be installed, but I can't find in the PATH or via pip"
+        exit 1
+    fi
 }
 
-if [ -n "$PIPENV_BIN" ];
-then
-    run "$PIPENV_BIN"
-else
+request_install_to_virtual_env () {
+    echo "Do you want to install pipenv into the current virtual environment: yes/no"
+    read ANSWER
+    if [ "$ANSWER" == "yes" ];
+    then
+        pip install pipenv
+        find_and_run_via_pip
+        run "$PIPENV_BIN"
+    else
+        echo "Aborting"
+    fi
+}
+
+request_install_to_user () {
+    echo "Do you want to install pipenv local to the user: yes/no"
+    read ANSWER
+    if [ "$ANSWER" == "yes" ];
+    then
+        pip install --user pipenv
+        PIPENV_BIN="$(python3 -m site --user-base)/bin/pipenv"
+        run "$PIPENV_BIN"
+    else
+        echo "Aborting"
+    fi
+}
+
+request_install () {
+    IS_IN_VIRTUAL_ENV=$(python -c "import sys; print(hasattr(sys, 'real_prefix'))")
+    if [ "$IS_IN_VIRTUAL_ENV" == "True" ];
+    then
+        request_install_to_virtual_env
+    else
+        request_install_to_user
+    fi
+}
+
+
+discover_pipenv_and_run() {
     PIPENV_BIN=$(command -v pipenv)
     if [ -n "$PIPENV_BIN" ];
     then
@@ -40,41 +86,16 @@ else
     else
         if pip show pipenv &> /dev/null;
         then
-            find_via_pip
-            if [ -n "$PIPENV_BIN" ];
-            then
-                run "$PIPENV_BIN"
-            else
-                echo "ERROR: pipenv seems to be installed, but I can't find in the PATH or via pip"
-                exit 1
-            fi
+            find_and_run_via_pip
         else
-            IS_IN_VIRTUAL_ENV=$(python -c "import sys; print(hasattr(sys, 'real_prefix'))")
-            if [ "$IS_IN_VIRTUAL_ENV" == "True" ];
-            then
-                echo "Do you want to install pipenv into the current virtual environment: yes/no"
-                read ANSWER
-                if [ "$ANSWER" == "yes" ];
-                then
-                    pip install pipenv
-                    find_via_pip
-                    run "$PIPENV_BIN"
-                else
-                    echo "Aborting"
-                fi
-            else
-                echo "Do you want to install pipenv local to the user: yes/no"
-                read ANSWER
-                if [ "$ANSWER" == "yes" ];
-                then
-                    pip install --user pipenv
-                    PIPENV_BIN="$(python3 -m site --user-base)/bin/pipenv"
-                    run "$PIPENV_BIN"
-                else
-                    echo "Aborting"
-                fi
-            fi
-
+            request_install_and_run
         fi
     fi
+}
+
+if [ -n "$PIPENV_BIN" ];
+then
+    run "$PIPENV_BIN"
+else
+    discover_pipenv_and_run
 fi
