Add ldd output

diff --git a/test b/test
--- a/test
+++ b/test
@@ -67,7 +67,14 @@ fi
 
 [ -z "${EXAPLUS-}" ] && export EXAPLUS="$(pwd)/downloads/EXAplus-6.0.10/exaplus"
 
+# Add ODBC lib to load path. Necessary on Travis to prevent "Can't open lib
+# '[...]/x86_64/libexaodbc-uo2214lv2.so' : file not found (0)" errors.
 set +u
+
+ldd downloads/EXASOL_ODBC-6.0.8/lib/linux/x86_64/libexaodbc-uo2214lv2.so
+export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/downloads/EXASOL_ODBC-6.0.8/lib/linux/x86_64
+ldd downloads/EXASOL_ODBC-6.0.8/lib/linux/x86_64/libexaodbc-uo2214lv2.so
+
 if [ ! -f "./tests/bin/activate" ]; then
     virtualenv --python "$(which python2)" "./tests"
 fi
@@ -117,8 +124,9 @@ function waitForLine {
 
 if [ -z ${EXASOLO+x} ]; then
 
-    trap cleanup EXIT
     RETURN_CODE=1
+    echo 'skipping cleanup'
+    # trap cleanup EXIT
     TEST_TMP_DIR="$(pwd)/udf-test-tmp"
 
     # Setup directory "exa" with pre-configured EXAConf to attach it to the exasoldb docker container
@@ -150,6 +158,7 @@ if [ -z ${EXASOLO+x} ]; then
     DB_HOST=172.17.0.2
     DB_PORT=8888
 
+    # $(find / -iname exaplus 2> /dev/null | head -n 1) \
     # need to import from within the container to avoid port conflicts
     docker cp tests/test/enginedb_small exasoldb:/tmp
     docker exec exasoldb bash -c 'cd /tmp/enginedb_small && /usr/opt/EXASuite-6/EXASolution-6.0.10/bin/Console/exaplus -c 127.0.0.1:8888 -u sys -p exasol -f /tmp/enginedb_small/import.sql'
@@ -174,3 +183,6 @@ set +e
 ( cd tests/test ; ./run_locally.sh --server "$DB_HOST:$DB_PORT" --test-config "$test_config" --)
 RETURN_CODE=$?
 exit $RETURN_CODE
+
+# Extract failed tests:
+# sed -n '/=\{70\}/,/^FAILED */{p}' setup_ec2.sh.out > setup_ec2.sh.out.failed
