Improve error message of language implementations in the UDFClient (#131)
- Return full but compact stack traces for user code exceptions in Java and Python UDFs
  - Java stack traces now contain also causes of Exceptions
  - Verbose stack frames inside the language implementations get still cleaned to make the exceptions easier to read
- Error codes now start at number 1000 (see https://softwareengineering.stackexchange.com/questions/209693/best-practices-to-create-error-codes-pattern-for-an-enterprise-project-in-c)
- Add error codes to the language implementations for Java, Python and R in the UDFClient
- Add missing error codes to exaudflib
- Introduce new name schema for error codes in exaudflib of the form [FEW]-UDF.CL.LIB-1000
- Add precommit githook which searches for duplicated error codes
- Replace abort()-calls in the language implementations with exceptions

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,28 +1,12 @@
 #!/bin/bash
-# define colors for use in output
-green='\033[0;32m'
-no_color='\033[0m'
-grey='\033[0;90m'
+set -o errexit
+set -o nounset
+set -o pipefail
 
-# Check whether any submodule is about to be updated with the
-# commit. Ask the user for confirmation.
-# --Chaitanya Gupta
-
-echo -e "Checking submodules ${grey}(pre-commit hook)${no_color} "
-
-# Jump to the current project's root directory (the one containing
-# .git/)
-ROOT_DIR=$(git rev-parse --show-cdup)
-
-SUBMODULES=$(grep path ${ROOT_DIR}.gitmodules | sed 's/^.*path = //' | sort)
-
-CURRENT_GITMODULES="$ROOT_DIR.current_gitmodules"
-if [ -f "$CURRENT_GITMODULES" ]
-then
-  rm "$CURRENT_GITMODULES"
-fi
-for SUB in $SUBMODULES
-do
-    git ls-files -s "$SUB" >> "$CURRENT_GITMODULES"
-done
-git add "$CURRENT_GITMODULES"
+REPO_DIR=$(git rev-parse --show-toplevel)
+GITHOOKS_PATH="$REPO_DIR/githooks"
+pushd $REPO_DIR
+bash $GITHOOKS_PATH/update_current_submodules_file.sh
+echo "Searching for duplicated error codes in repository (pre-commit hook)"
+bash find_duplicate_error_codes.sh
+popd
